package chandoswing;

/**
 *
 * @author yportlamo
 */
public class Ej24_EventosDesdeCodigoGeneral extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Ej24_EventosDesdeCodigoGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiTexto = new java.awt.Label();
        txtDato = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiTexto.setText("etiTexto");
        etiTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiTextoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                etiTextoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                etiTextoMouseReleased(evt);
            }
        });

        txtDato.setText("txtDato");
        txtDato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDatoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etiTextoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiTextoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_etiTextoMouseReleased

    private void etiTextoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiTextoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_etiTextoMousePressed

    private void etiTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiTextoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_etiTextoMouseExited

    private void etiTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiTextoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_etiTextoMouseEntered

    private void etiTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiTextoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_etiTextoMouseClicked

    private void txtDatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatoKeyReleased

    private void txtDatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej24_EventosDesdeCodigoGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej24_EventosDesdeCodigoGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej24_EventosDesdeCodigoGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej24_EventosDesdeCodigoGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej24_EventosDesdeCodigoGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label etiTexto;
    private java.awt.Label txtDato;
    // End of variables declaration//GEN-END:variables
}
